/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ComplianceServicePartitionedLibraryInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOfInvestor"
      | "doPreTransferCheckPartitioned"
      | "getLockTime"
      | "isOmnibusTBE"
      | "newPreTransferCheck"
      | "preTransferCheck"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOfInvestor",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "doPreTransferCheckPartitioned",
    values: [
      AddressLike[],
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockTime",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "isOmnibusTBE",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "newPreTransferCheck",
    values: [
      AddressLike[],
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "preTransferCheck",
    values: [AddressLike[], AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "balanceOfInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doPreTransferCheckPartitioned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOmnibusTBE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newPreTransferCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preTransferCheck",
    data: BytesLike
  ): Result;
}

export interface ComplianceServicePartitionedLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceServicePartitionedLibrary;
  waitForDeployment(): Promise<this>;

  interface: ComplianceServicePartitionedLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOfInvestor: TypedContractMethod<
    [_services: AddressLike[], _wallet: AddressLike],
    [bigint],
    "view"
  >;

  doPreTransferCheckPartitioned: TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _balanceFrom: BigNumberish,
      _paused: boolean
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;

  getLockTime: TypedContractMethod<
    [
      _complianceConfiguration: AddressLike,
      _partitionRegion: BigNumberish,
      _checkFlowback: boolean
    ],
    [bigint],
    "view"
  >;

  isOmnibusTBE: TypedContractMethod<
    [_omnibusTBE: AddressLike, _from: AddressLike],
    [boolean],
    "view"
  >;

  newPreTransferCheck: TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _balanceFrom: BigNumberish,
      _paused: boolean
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;

  preTransferCheck: TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOfInvestor"
  ): TypedContractMethod<
    [_services: AddressLike[], _wallet: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "doPreTransferCheckPartitioned"
  ): TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _balanceFrom: BigNumberish,
      _paused: boolean
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLockTime"
  ): TypedContractMethod<
    [
      _complianceConfiguration: AddressLike,
      _partitionRegion: BigNumberish,
      _checkFlowback: boolean
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOmnibusTBE"
  ): TypedContractMethod<
    [_omnibusTBE: AddressLike, _from: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "newPreTransferCheck"
  ): TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _balanceFrom: BigNumberish,
      _paused: boolean
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "preTransferCheck"
  ): TypedContractMethod<
    [
      _services: AddressLike[],
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish
    ],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;

  filters: {};
}
