/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RegistryServiceDataStoreInterface extends Interface {
  getFunction(nameOrSignature: "attributes"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attributes",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "attributes", data: BytesLike): Result;
}

export interface RegistryServiceDataStore extends BaseContract {
  connect(runner?: ContractRunner | null): RegistryServiceDataStore;
  waitForDeployment(): Promise<this>;

  interface: RegistryServiceDataStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attributes: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, string] & {
        value: bigint;
        expiry: bigint;
        proofHash: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attributes"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, string] & {
        value: bigint;
        expiry: bigint;
        proofHash: string;
      }
    ],
    "view"
  >;

  filters: {};
}
