/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InvestorLockManagerPartitionedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_CONFIGURATION_SERVICE"
      | "COMPLIANCE_SERVICE"
      | "DS_TOKEN"
      | "LOCK_MANAGER"
      | "OMNIBUS_TBE_CONTROLLER"
      | "PARTITIONS_MANAGER"
      | "REGISTRY_SERVICE"
      | "ROLE_EXCHANGE"
      | "ROLE_ISSUER"
      | "ROLE_MASTER"
      | "ROLE_NONE"
      | "ROLE_TRANSFER_AGENT"
      | "SECURITIZE_SWAP"
      | "TOKEN_ISSUER"
      | "TOKEN_REALLOCATOR"
      | "TRANSACTION_RELAYER"
      | "TRUST_SERVICE"
      | "UNUSED_1"
      | "WALLET_MANAGER"
      | "WALLET_REGISTRAR"
      | "addManualLockRecord(address,uint256,string,uint256)"
      | "addManualLockRecord(address,uint256,string,uint256,bytes32)"
      | "contractOwner"
      | "createLockForHolder"
      | "createLockForInvestor(string,uint256,uint256,string,uint256,bytes32)"
      | "createLockForInvestor(string,uint256,uint256,string,uint256)"
      | "getDSService"
      | "getTransferableTokens(address,uint256)"
      | "getTransferableTokens(address,uint256,bytes32)"
      | "getTransferableTokensForHolder"
      | "getTransferableTokensForInvestor(string,uint256,bytes32)"
      | "getTransferableTokensForInvestor(string,uint256)"
      | "getVersion"
      | "initialize"
      | "isInvestorLocked"
      | "isOwner"
      | "lockCount(address,bytes32)"
      | "lockCount(address)"
      | "lockCountForHolder"
      | "lockCountForInvestor(string,bytes32)"
      | "lockCountForInvestor(string)"
      | "lockInfo(address,uint256,bytes32)"
      | "lockInfo(address,uint256)"
      | "lockInfoForHolder"
      | "lockInfoForInvestor(string,uint256)"
      | "lockInfoForInvestor(string,uint256,bytes32)"
      | "lockInvestor"
      | "owner"
      | "removeLockRecord(address,uint256,bytes32)"
      | "removeLockRecord(address,uint256)"
      | "removeLockRecordForHolder"
      | "removeLockRecordForInvestor(string,uint256)"
      | "removeLockRecordForInvestor(string,uint256,bytes32)"
      | "renounceOwnership"
      | "setDSService"
      | "transferOwnership"
      | "unlockInvestor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DSServiceSet"
      | "HolderLocked"
      | "HolderLockedPartition"
      | "HolderUnlocked"
      | "HolderUnlockedPartition"
      | "Initialized"
      | "InvestorFullyLocked"
      | "InvestorFullyUnlocked"
      | "Locked"
      | "LockedPartition"
      | "OwnershipTransferred"
      | "Unlocked"
      | "UnlockedPartition"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_CONFIGURATION_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMPLIANCE_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DS_TOKEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LOCK_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OMNIBUS_TBE_CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARTITIONS_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRY_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_EXCHANGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_ISSUER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_MASTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROLE_NONE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ROLE_TRANSFER_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECURITIZE_SWAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_ISSUER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_REALLOCATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSACTION_RELAYER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRUST_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "UNUSED_1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WALLET_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WALLET_REGISTRAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addManualLockRecord(address,uint256,string,uint256)",
    values: [AddressLike, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addManualLockRecord(address,uint256,string,uint256,bytes32)",
    values: [AddressLike, BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLockForHolder",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createLockForInvestor(string,uint256,uint256,string,uint256,bytes32)",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createLockForInvestor(string,uint256,uint256,string,uint256)",
    values: [string, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDSService",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferableTokens(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferableTokens(address,uint256,bytes32)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferableTokensForHolder",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferableTokensForInvestor(string,uint256,bytes32)",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferableTokensForInvestor(string,uint256)",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInvestorLocked",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockCount(address,bytes32)",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCount(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCountForHolder",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCountForInvestor(string,bytes32)",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCountForInvestor(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInfo(address,uint256,bytes32)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInfo(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInfoForHolder",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInfoForInvestor(string,uint256)",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInfoForInvestor(string,uint256,bytes32)",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockInvestor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLockRecord(address,uint256,bytes32)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLockRecord(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLockRecordForHolder",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLockRecordForInvestor(string,uint256)",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLockRecordForInvestor(string,uint256,bytes32)",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDSService",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockInvestor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_CONFIGURATION_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMPLIANCE_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DS_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OMNIBUS_TBE_CONTROLLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARTITIONS_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRY_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_EXCHANGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_ISSUER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_MASTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROLE_NONE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_TRANSFER_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECURITIZE_SWAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_ISSUER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_REALLOCATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSACTION_RELAYER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRUST_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UNUSED_1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WALLET_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WALLET_REGISTRAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManualLockRecord(address,uint256,string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManualLockRecord(address,uint256,string,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLockForHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLockForInvestor(string,uint256,uint256,string,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLockForInvestor(string,uint256,uint256,string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDSService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferableTokens(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferableTokens(address,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferableTokensForHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferableTokensForInvestor(string,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferableTokensForInvestor(string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInvestorLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockCount(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCount(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCountForHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCountForInvestor(string,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCountForInvestor(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInfo(address,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInfo(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInfoForHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInfoForInvestor(string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInfoForInvestor(string,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLockRecord(address,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLockRecord(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLockRecordForHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLockRecordForInvestor(string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLockRecordForInvestor(string,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDSService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockInvestor",
    data: BytesLike
  ): Result;
}

export namespace DSServiceSetEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    serviceAddress: AddressLike
  ];
  export type OutputTuple = [serviceId: bigint, serviceAddress: string];
  export interface OutputObject {
    serviceId: bigint;
    serviceAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HolderLockedEvent {
  export type InputTuple = [
    holderId: string,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish
  ];
  export type OutputTuple = [
    holderId: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint
  ];
  export interface OutputObject {
    holderId: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HolderLockedPartitionEvent {
  export type InputTuple = [
    investorId: string,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish,
    partition: BytesLike
  ];
  export type OutputTuple = [
    investorId: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint,
    partition: string
  ];
  export interface OutputObject {
    investorId: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
    partition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HolderUnlockedEvent {
  export type InputTuple = [
    holderId: string,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish
  ];
  export type OutputTuple = [
    holderId: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint
  ];
  export interface OutputObject {
    holderId: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HolderUnlockedPartitionEvent {
  export type InputTuple = [
    investorId: string,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish,
    partition: BytesLike
  ];
  export type OutputTuple = [
    investorId: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint,
    partition: string
  ];
  export interface OutputObject {
    investorId: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
    partition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorFullyLockedEvent {
  export type InputTuple = [investorId: string];
  export type OutputTuple = [investorId: string];
  export interface OutputObject {
    investorId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorFullyUnlockedEvent {
  export type InputTuple = [investorId: string];
  export type OutputTuple = [investorId: string];
  export interface OutputObject {
    investorId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [
    who: AddressLike,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish
  ];
  export type OutputTuple = [
    who: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint
  ];
  export interface OutputObject {
    who: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedPartitionEvent {
  export type InputTuple = [
    who: AddressLike,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish,
    partition: BytesLike
  ];
  export type OutputTuple = [
    who: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint,
    partition: string
  ];
  export interface OutputObject {
    who: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
    partition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedEvent {
  export type InputTuple = [
    who: AddressLike,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish
  ];
  export type OutputTuple = [
    who: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint
  ];
  export interface OutputObject {
    who: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedPartitionEvent {
  export type InputTuple = [
    who: AddressLike,
    value: BigNumberish,
    reason: BigNumberish,
    reasonString: string,
    releaseTime: BigNumberish,
    partition: BytesLike
  ];
  export type OutputTuple = [
    who: string,
    value: bigint,
    reason: bigint,
    reasonString: string,
    releaseTime: bigint,
    partition: string
  ];
  export interface OutputObject {
    who: string;
    value: bigint;
    reason: bigint;
    reasonString: string;
    releaseTime: bigint;
    partition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InvestorLockManagerPartitioned extends BaseContract {
  connect(runner?: ContractRunner | null): InvestorLockManagerPartitioned;
  waitForDeployment(): Promise<this>;

  interface: InvestorLockManagerPartitionedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_CONFIGURATION_SERVICE: TypedContractMethod<[], [bigint], "view">;

  COMPLIANCE_SERVICE: TypedContractMethod<[], [bigint], "view">;

  DS_TOKEN: TypedContractMethod<[], [bigint], "view">;

  LOCK_MANAGER: TypedContractMethod<[], [bigint], "view">;

  OMNIBUS_TBE_CONTROLLER: TypedContractMethod<[], [bigint], "view">;

  PARTITIONS_MANAGER: TypedContractMethod<[], [bigint], "view">;

  REGISTRY_SERVICE: TypedContractMethod<[], [bigint], "view">;

  ROLE_EXCHANGE: TypedContractMethod<[], [bigint], "view">;

  ROLE_ISSUER: TypedContractMethod<[], [bigint], "view">;

  ROLE_MASTER: TypedContractMethod<[], [bigint], "view">;

  ROLE_NONE: TypedContractMethod<[], [bigint], "view">;

  ROLE_TRANSFER_AGENT: TypedContractMethod<[], [bigint], "view">;

  SECURITIZE_SWAP: TypedContractMethod<[], [bigint], "view">;

  TOKEN_ISSUER: TypedContractMethod<[], [bigint], "view">;

  TOKEN_REALLOCATOR: TypedContractMethod<[], [bigint], "view">;

  TRANSACTION_RELAYER: TypedContractMethod<[], [bigint], "view">;

  TRUST_SERVICE: TypedContractMethod<[], [bigint], "view">;

  UNUSED_1: TypedContractMethod<[], [bigint], "view">;

  WALLET_MANAGER: TypedContractMethod<[], [bigint], "view">;

  WALLET_REGISTRAR: TypedContractMethod<[], [bigint], "view">;

  "addManualLockRecord(address,uint256,string,uint256)": TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: string, arg3: BigNumberish],
    [void],
    "view"
  >;

  "addManualLockRecord(address,uint256,string,uint256,bytes32)": TypedContractMethod<
    [
      _to: AddressLike,
      _valueLocked: BigNumberish,
      _reason: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  contractOwner: TypedContractMethod<[], [string], "view">;

  createLockForHolder: TypedContractMethod<
    [
      _holderId: string,
      _valueLocked: BigNumberish,
      _reasonCode: BigNumberish,
      _reasonString: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "createLockForInvestor(string,uint256,uint256,string,uint256,bytes32)": TypedContractMethod<
    [
      _investorId: string,
      _valueLocked: BigNumberish,
      _reasonCode: BigNumberish,
      _reasonString: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "createLockForInvestor(string,uint256,uint256,string,uint256)": TypedContractMethod<
    [
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: string,
      arg4: BigNumberish
    ],
    [void],
    "view"
  >;

  getDSService: TypedContractMethod<
    [_serviceId: BigNumberish],
    [string],
    "view"
  >;

  "getTransferableTokens(address,uint256)": TypedContractMethod<
    [_who: AddressLike, _time: BigNumberish],
    [bigint],
    "view"
  >;

  "getTransferableTokens(address,uint256,bytes32)": TypedContractMethod<
    [_who: AddressLike, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;

  getTransferableTokensForHolder: TypedContractMethod<
    [_holderId: string, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;

  "getTransferableTokensForInvestor(string,uint256,bytes32)": TypedContractMethod<
    [_investorId: string, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;

  "getTransferableTokensForInvestor(string,uint256)": TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getVersion: TypedContractMethod<[], [bigint[]], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  isInvestorLocked: TypedContractMethod<
    [_investorId: string],
    [boolean],
    "view"
  >;

  isOwner: TypedContractMethod<[], [boolean], "view">;

  "lockCount(address,bytes32)": TypedContractMethod<
    [_who: AddressLike, _partition: BytesLike],
    [bigint],
    "view"
  >;

  "lockCount(address)": TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  lockCountForHolder: TypedContractMethod<
    [_holderId: string, _partition: BytesLike],
    [bigint],
    "view"
  >;

  "lockCountForInvestor(string,bytes32)": TypedContractMethod<
    [_investorId: string, _partition: BytesLike],
    [bigint],
    "view"
  >;

  "lockCountForInvestor(string)": TypedContractMethod<
    [arg0: string],
    [bigint],
    "view"
  >;

  "lockInfo(address,uint256,bytes32)": TypedContractMethod<
    [_who: AddressLike, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;

  "lockInfo(address,uint256)": TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, string, bigint, bigint]],
    "view"
  >;

  lockInfoForHolder: TypedContractMethod<
    [_holderId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;

  "lockInfoForInvestor(string,uint256)": TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [[bigint, string, bigint, bigint]],
    "view"
  >;

  "lockInfoForInvestor(string,uint256,bytes32)": TypedContractMethod<
    [_investorId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;

  lockInvestor: TypedContractMethod<
    [_investorId: string],
    [boolean],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  "removeLockRecord(address,uint256,bytes32)": TypedContractMethod<
    [_to: AddressLike, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;

  "removeLockRecord(address,uint256)": TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  removeLockRecordForHolder: TypedContractMethod<
    [_holderId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;

  "removeLockRecordForInvestor(string,uint256)": TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  "removeLockRecordForInvestor(string,uint256,bytes32)": TypedContractMethod<
    [_investorId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDSService: TypedContractMethod<
    [_serviceId: BigNumberish, _address: AddressLike],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockInvestor: TypedContractMethod<
    [_investorId: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_CONFIGURATION_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COMPLIANCE_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DS_TOKEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OMNIBUS_TBE_CONTROLLER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARTITIONS_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTRY_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_EXCHANGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_ISSUER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_MASTER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_TRANSFER_AGENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECURITIZE_SWAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_ISSUER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_REALLOCATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRANSACTION_RELAYER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRUST_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNUSED_1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WALLET_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WALLET_REGISTRAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addManualLockRecord(address,uint256,string,uint256)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: string, arg3: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "addManualLockRecord(address,uint256,string,uint256,bytes32)"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _valueLocked: BigNumberish,
      _reason: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createLockForHolder"
  ): TypedContractMethod<
    [
      _holderId: string,
      _valueLocked: BigNumberish,
      _reasonCode: BigNumberish,
      _reasonString: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createLockForInvestor(string,uint256,uint256,string,uint256,bytes32)"
  ): TypedContractMethod<
    [
      _investorId: string,
      _valueLocked: BigNumberish,
      _reasonCode: BigNumberish,
      _reasonString: string,
      _releaseTime: BigNumberish,
      _partition: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createLockForInvestor(string,uint256,uint256,string,uint256)"
  ): TypedContractMethod<
    [
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: string,
      arg4: BigNumberish
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDSService"
  ): TypedContractMethod<[_serviceId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTransferableTokens(address,uint256)"
  ): TypedContractMethod<
    [_who: AddressLike, _time: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferableTokens(address,uint256,bytes32)"
  ): TypedContractMethod<
    [_who: AddressLike, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferableTokensForHolder"
  ): TypedContractMethod<
    [_holderId: string, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferableTokensForInvestor(string,uint256,bytes32)"
  ): TypedContractMethod<
    [_investorId: string, _time: BigNumberish, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferableTokensForInvestor(string,uint256)"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isInvestorLocked"
  ): TypedContractMethod<[_investorId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockCount(address,bytes32)"
  ): TypedContractMethod<
    [_who: AddressLike, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCount(address)"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockCountForHolder"
  ): TypedContractMethod<
    [_holderId: string, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCountForInvestor(string,bytes32)"
  ): TypedContractMethod<
    [_investorId: string, _partition: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCountForInvestor(string)"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockInfo(address,uint256,bytes32)"
  ): TypedContractMethod<
    [_who: AddressLike, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockInfo(address,uint256)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, string, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockInfoForHolder"
  ): TypedContractMethod<
    [_holderId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockInfoForInvestor(string,uint256)"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [[bigint, string, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockInfoForInvestor(string,uint256,bytes32)"
  ): TypedContractMethod<
    [_investorId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [
      [bigint, string, bigint, bigint] & {
        reasonCode: bigint;
        reasonString: string;
        value: bigint;
        autoReleaseTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockInvestor"
  ): TypedContractMethod<[_investorId: string], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLockRecord(address,uint256,bytes32)"
  ): TypedContractMethod<
    [_to: AddressLike, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLockRecord(address,uint256)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLockRecordForHolder"
  ): TypedContractMethod<
    [_holderId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLockRecordForInvestor(string,uint256)"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeLockRecordForInvestor(string,uint256,bytes32)"
  ): TypedContractMethod<
    [_investorId: string, _lockIndex: BigNumberish, _partition: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDSService"
  ): TypedContractMethod<
    [_serviceId: BigNumberish, _address: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockInvestor"
  ): TypedContractMethod<[_investorId: string], [boolean], "nonpayable">;

  getEvent(
    key: "DSServiceSet"
  ): TypedContractEvent<
    DSServiceSetEvent.InputTuple,
    DSServiceSetEvent.OutputTuple,
    DSServiceSetEvent.OutputObject
  >;
  getEvent(
    key: "HolderLocked"
  ): TypedContractEvent<
    HolderLockedEvent.InputTuple,
    HolderLockedEvent.OutputTuple,
    HolderLockedEvent.OutputObject
  >;
  getEvent(
    key: "HolderLockedPartition"
  ): TypedContractEvent<
    HolderLockedPartitionEvent.InputTuple,
    HolderLockedPartitionEvent.OutputTuple,
    HolderLockedPartitionEvent.OutputObject
  >;
  getEvent(
    key: "HolderUnlocked"
  ): TypedContractEvent<
    HolderUnlockedEvent.InputTuple,
    HolderUnlockedEvent.OutputTuple,
    HolderUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "HolderUnlockedPartition"
  ): TypedContractEvent<
    HolderUnlockedPartitionEvent.InputTuple,
    HolderUnlockedPartitionEvent.OutputTuple,
    HolderUnlockedPartitionEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "InvestorFullyLocked"
  ): TypedContractEvent<
    InvestorFullyLockedEvent.InputTuple,
    InvestorFullyLockedEvent.OutputTuple,
    InvestorFullyLockedEvent.OutputObject
  >;
  getEvent(
    key: "InvestorFullyUnlocked"
  ): TypedContractEvent<
    InvestorFullyUnlockedEvent.InputTuple,
    InvestorFullyUnlockedEvent.OutputTuple,
    InvestorFullyUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "LockedPartition"
  ): TypedContractEvent<
    LockedPartitionEvent.InputTuple,
    LockedPartitionEvent.OutputTuple,
    LockedPartitionEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Unlocked"
  ): TypedContractEvent<
    UnlockedEvent.InputTuple,
    UnlockedEvent.OutputTuple,
    UnlockedEvent.OutputObject
  >;
  getEvent(
    key: "UnlockedPartition"
  ): TypedContractEvent<
    UnlockedPartitionEvent.InputTuple,
    UnlockedPartitionEvent.OutputTuple,
    UnlockedPartitionEvent.OutputObject
  >;

  filters: {
    "DSServiceSet(uint256,address)": TypedContractEvent<
      DSServiceSetEvent.InputTuple,
      DSServiceSetEvent.OutputTuple,
      DSServiceSetEvent.OutputObject
    >;
    DSServiceSet: TypedContractEvent<
      DSServiceSetEvent.InputTuple,
      DSServiceSetEvent.OutputTuple,
      DSServiceSetEvent.OutputObject
    >;

    "HolderLocked(string,uint256,uint256,string,uint256)": TypedContractEvent<
      HolderLockedEvent.InputTuple,
      HolderLockedEvent.OutputTuple,
      HolderLockedEvent.OutputObject
    >;
    HolderLocked: TypedContractEvent<
      HolderLockedEvent.InputTuple,
      HolderLockedEvent.OutputTuple,
      HolderLockedEvent.OutputObject
    >;

    "HolderLockedPartition(string,uint256,uint256,string,uint256,bytes32)": TypedContractEvent<
      HolderLockedPartitionEvent.InputTuple,
      HolderLockedPartitionEvent.OutputTuple,
      HolderLockedPartitionEvent.OutputObject
    >;
    HolderLockedPartition: TypedContractEvent<
      HolderLockedPartitionEvent.InputTuple,
      HolderLockedPartitionEvent.OutputTuple,
      HolderLockedPartitionEvent.OutputObject
    >;

    "HolderUnlocked(string,uint256,uint256,string,uint256)": TypedContractEvent<
      HolderUnlockedEvent.InputTuple,
      HolderUnlockedEvent.OutputTuple,
      HolderUnlockedEvent.OutputObject
    >;
    HolderUnlocked: TypedContractEvent<
      HolderUnlockedEvent.InputTuple,
      HolderUnlockedEvent.OutputTuple,
      HolderUnlockedEvent.OutputObject
    >;

    "HolderUnlockedPartition(string,uint256,uint256,string,uint256,bytes32)": TypedContractEvent<
      HolderUnlockedPartitionEvent.InputTuple,
      HolderUnlockedPartitionEvent.OutputTuple,
      HolderUnlockedPartitionEvent.OutputObject
    >;
    HolderUnlockedPartition: TypedContractEvent<
      HolderUnlockedPartitionEvent.InputTuple,
      HolderUnlockedPartitionEvent.OutputTuple,
      HolderUnlockedPartitionEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "InvestorFullyLocked(string)": TypedContractEvent<
      InvestorFullyLockedEvent.InputTuple,
      InvestorFullyLockedEvent.OutputTuple,
      InvestorFullyLockedEvent.OutputObject
    >;
    InvestorFullyLocked: TypedContractEvent<
      InvestorFullyLockedEvent.InputTuple,
      InvestorFullyLockedEvent.OutputTuple,
      InvestorFullyLockedEvent.OutputObject
    >;

    "InvestorFullyUnlocked(string)": TypedContractEvent<
      InvestorFullyUnlockedEvent.InputTuple,
      InvestorFullyUnlockedEvent.OutputTuple,
      InvestorFullyUnlockedEvent.OutputObject
    >;
    InvestorFullyUnlocked: TypedContractEvent<
      InvestorFullyUnlockedEvent.InputTuple,
      InvestorFullyUnlockedEvent.OutputTuple,
      InvestorFullyUnlockedEvent.OutputObject
    >;

    "Locked(address,uint256,uint256,string,uint256)": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "LockedPartition(address,uint256,uint256,string,uint256,bytes32)": TypedContractEvent<
      LockedPartitionEvent.InputTuple,
      LockedPartitionEvent.OutputTuple,
      LockedPartitionEvent.OutputObject
    >;
    LockedPartition: TypedContractEvent<
      LockedPartitionEvent.InputTuple,
      LockedPartitionEvent.OutputTuple,
      LockedPartitionEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Unlocked(address,uint256,uint256,string,uint256)": TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;
    Unlocked: TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;

    "UnlockedPartition(address,uint256,uint256,string,uint256,bytes32)": TypedContractEvent<
      UnlockedPartitionEvent.InputTuple,
      UnlockedPartitionEvent.OutputTuple,
      UnlockedPartitionEvent.OutputObject
    >;
    UnlockedPartition: TypedContractEvent<
      UnlockedPartitionEvent.InputTuple,
      UnlockedPartitionEvent.OutputTuple,
      UnlockedPartitionEvent.OutputObject
    >;
  };
}
