/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DSTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_CONFIGURATION_SERVICE"
      | "COMPLIANCE_SERVICE"
      | "DS_TOKEN"
      | "LOCK_MANAGER"
      | "OMNIBUS_TBE_CONTROLLER"
      | "PARTITIONS_MANAGER"
      | "REGISTRY_SERVICE"
      | "ROLE_EXCHANGE"
      | "ROLE_ISSUER"
      | "ROLE_MASTER"
      | "ROLE_NONE"
      | "ROLE_TRANSFER_AGENT"
      | "SECURITIZE_SWAP"
      | "TOKEN_ISSUER"
      | "TOKEN_REALLOCATOR"
      | "TRANSACTION_RELAYER"
      | "TRUST_SERVICE"
      | "UNUSED_1"
      | "UPGRADE_INTERFACE_VERSION"
      | "WALLET_MANAGER"
      | "WALLET_REGISTRAR"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "balanceOfInvestor"
      | "burn"
      | "cap"
      | "contractOwner"
      | "decimals"
      | "decreaseApproval"
      | "emitOmnibusTBEEvent"
      | "emitOmnibusTBETransferEvent"
      | "emitOmnibusTransferEvent"
      | "getDSService"
      | "getVersion"
      | "getWalletAt"
      | "increaseApproval"
      | "initialize(string,string,uint8)"
      | "initialize()"
      | "isOwner"
      | "isPaused"
      | "issueTokens"
      | "issueTokensCustom"
      | "issueTokensWithMultipleLocks"
      | "issueTokensWithNoCompliance"
      | "name"
      | "omnibusBurn"
      | "omnibusSeize"
      | "owner"
      | "pause"
      | "preTransferCheck"
      | "proxiableUUID"
      | "renounceOwnership"
      | "seize"
      | "setCap"
      | "setDSService"
      | "setFeature"
      | "setFeatures"
      | "supportedFeatures"
      | "symbol"
      | "totalIssued"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "unpause"
      | "updateOmnibusInvestorBalance"
      | "upgradeToAndCall"
      | "walletCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "Burn"
      | "DSServiceSet"
      | "Initialized"
      | "Issue"
      | "OmnibusBurn"
      | "OmnibusDeposit"
      | "OmnibusSeize"
      | "OmnibusTBEOperation"
      | "OmnibusTBETransfer"
      | "OmnibusTransfer"
      | "OmnibusWithdraw"
      | "OwnershipTransferred"
      | "Pause"
      | "Seize"
      | "Transfer"
      | "Unpause"
      | "Upgraded"
      | "WalletAdded"
      | "WalletRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_CONFIGURATION_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMPLIANCE_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DS_TOKEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LOCK_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OMNIBUS_TBE_CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARTITIONS_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRY_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_EXCHANGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_ISSUER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_MASTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROLE_NONE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ROLE_TRANSFER_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECURITIZE_SWAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_ISSUER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_REALLOCATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSACTION_RELAYER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRUST_SERVICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "UNUSED_1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WALLET_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WALLET_REGISTRAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfInvestor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "cap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseApproval",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitOmnibusTBEEvent",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitOmnibusTBETransferEvent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitOmnibusTransferEvent",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDSService",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseApproval",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(string,string,uint8)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "issueTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTokensCustom",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTokensWithMultipleLocks",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      string,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTokensWithNoCompliance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "omnibusBurn",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "omnibusSeize",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "preTransferCheck",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seize",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDSService",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeature",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedFeatures",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalIssued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateOmnibusInvestorBalance",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_CONFIGURATION_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMPLIANCE_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DS_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OMNIBUS_TBE_CONTROLLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARTITIONS_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRY_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_EXCHANGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_ISSUER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_MASTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROLE_NONE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_TRANSFER_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECURITIZE_SWAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_ISSUER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_REALLOCATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSACTION_RELAYER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRUST_SERVICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UNUSED_1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WALLET_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WALLET_REGISTRAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitOmnibusTBEEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitOmnibusTBETransferEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitOmnibusTransferEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDSService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWalletAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(string,string,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTokensCustom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTokensWithMultipleLocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTokensWithNoCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "omnibusBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "omnibusSeize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "preTransferCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDSService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeature", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedFeatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalIssued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateOmnibusInvestorBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletCount",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnEvent {
  export type InputTuple = [
    burner: AddressLike,
    value: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [burner: string, value: bigint, reason: string];
  export interface OutputObject {
    burner: string;
    value: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DSServiceSetEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    serviceAddress: AddressLike
  ];
  export type OutputTuple = [serviceId: bigint, serviceAddress: string];
  export interface OutputObject {
    serviceId: bigint;
    serviceAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssueEvent {
  export type InputTuple = [
    to: AddressLike,
    value: BigNumberish,
    valueLocked: BigNumberish
  ];
  export type OutputTuple = [to: string, value: bigint, valueLocked: bigint];
  export interface OutputObject {
    to: string;
    value: bigint;
    valueLocked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusBurnEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    who: AddressLike,
    value: BigNumberish,
    reason: string,
    assetTrackingMode: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    who: string,
    value: bigint,
    reason: string,
    assetTrackingMode: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    who: string;
    value: bigint;
    reason: string;
    assetTrackingMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusDepositEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    assetTrackingMode: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    to: string,
    value: bigint,
    assetTrackingMode: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    to: string;
    value: bigint;
    assetTrackingMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusSeizeEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    from: AddressLike,
    value: BigNumberish,
    reason: string,
    assetTrackingMode: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    from: string,
    value: bigint,
    reason: string,
    assetTrackingMode: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    from: string;
    value: bigint;
    reason: string;
    assetTrackingMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusTBEOperationEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    totalDelta: BigNumberish,
    accreditedDelta: BigNumberish,
    usAccreditedDelta: BigNumberish,
    usTotalDelta: BigNumberish,
    jpTotalDelta: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    totalDelta: bigint,
    accreditedDelta: bigint,
    usAccreditedDelta: bigint,
    usTotalDelta: bigint,
    jpTotalDelta: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    totalDelta: bigint;
    accreditedDelta: bigint;
    usAccreditedDelta: bigint;
    usTotalDelta: bigint;
    jpTotalDelta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusTBETransferEvent {
  export type InputTuple = [omnibusWallet: AddressLike, externalId: string];
  export type OutputTuple = [omnibusWallet: string, externalId: string];
  export interface OutputObject {
    omnibusWallet: string;
    externalId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusTransferEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    assetTrackingMode: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    from: string,
    to: string,
    value: bigint,
    assetTrackingMode: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    from: string;
    to: string;
    value: bigint;
    assetTrackingMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OmnibusWithdrawEvent {
  export type InputTuple = [
    omnibusWallet: AddressLike,
    from: AddressLike,
    value: BigNumberish,
    assetTrackingMode: BigNumberish
  ];
  export type OutputTuple = [
    omnibusWallet: string,
    from: string,
    value: bigint,
    assetTrackingMode: bigint
  ];
  export interface OutputObject {
    omnibusWallet: string;
    from: string;
    value: bigint;
    assetTrackingMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeizeEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    value: bigint,
    reason: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletAddedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletRemovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DSToken extends BaseContract {
  connect(runner?: ContractRunner | null): DSToken;
  waitForDeployment(): Promise<this>;

  interface: DSTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_CONFIGURATION_SERVICE: TypedContractMethod<[], [bigint], "view">;

  COMPLIANCE_SERVICE: TypedContractMethod<[], [bigint], "view">;

  DS_TOKEN: TypedContractMethod<[], [bigint], "view">;

  LOCK_MANAGER: TypedContractMethod<[], [bigint], "view">;

  OMNIBUS_TBE_CONTROLLER: TypedContractMethod<[], [bigint], "view">;

  PARTITIONS_MANAGER: TypedContractMethod<[], [bigint], "view">;

  REGISTRY_SERVICE: TypedContractMethod<[], [bigint], "view">;

  ROLE_EXCHANGE: TypedContractMethod<[], [bigint], "view">;

  ROLE_ISSUER: TypedContractMethod<[], [bigint], "view">;

  ROLE_MASTER: TypedContractMethod<[], [bigint], "view">;

  ROLE_NONE: TypedContractMethod<[], [bigint], "view">;

  ROLE_TRANSFER_AGENT: TypedContractMethod<[], [bigint], "view">;

  SECURITIZE_SWAP: TypedContractMethod<[], [bigint], "view">;

  TOKEN_ISSUER: TypedContractMethod<[], [bigint], "view">;

  TOKEN_REALLOCATOR: TypedContractMethod<[], [bigint], "view">;

  TRANSACTION_RELAYER: TypedContractMethod<[], [bigint], "view">;

  TRUST_SERVICE: TypedContractMethod<[], [bigint], "view">;

  UNUSED_1: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  WALLET_MANAGER: TypedContractMethod<[], [bigint], "view">;

  WALLET_REGISTRAR: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [_owner: AddressLike, _spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [_spender: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[_owner: AddressLike], [bigint], "view">;

  balanceOfInvestor: TypedContractMethod<[_id: string], [bigint], "view">;

  burn: TypedContractMethod<
    [_who: AddressLike, _value: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  cap: TypedContractMethod<[], [bigint], "view">;

  contractOwner: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseApproval: TypedContractMethod<
    [_spender: AddressLike, _subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  emitOmnibusTBEEvent: TypedContractMethod<
    [
      omnibusWallet: AddressLike,
      totalDelta: BigNumberish,
      accreditedDelta: BigNumberish,
      usAccreditedDelta: BigNumberish,
      usTotalDelta: BigNumberish,
      jpTotalDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitOmnibusTBETransferEvent: TypedContractMethod<
    [omnibusWallet: AddressLike, externalId: string],
    [void],
    "nonpayable"
  >;

  emitOmnibusTransferEvent: TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getDSService: TypedContractMethod<
    [_serviceId: BigNumberish],
    [string],
    "view"
  >;

  getVersion: TypedContractMethod<[], [bigint[]], "view">;

  getWalletAt: TypedContractMethod<[_index: BigNumberish], [string], "view">;

  increaseApproval: TypedContractMethod<
    [_spender: AddressLike, _addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  "initialize(string,string,uint8)": TypedContractMethod<
    [_name: string, _symbol: string, _decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  "initialize()": TypedContractMethod<[], [void], "nonpayable">;

  isOwner: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  issueTokens: TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  issueTokensCustom: TypedContractMethod<
    [
      _to: AddressLike,
      _value: BigNumberish,
      _issuanceTime: BigNumberish,
      _valueLocked: BigNumberish,
      _reason: string,
      _releaseTime: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  issueTokensWithMultipleLocks: TypedContractMethod<
    [
      _to: AddressLike,
      _value: BigNumberish,
      _issuanceTime: BigNumberish,
      _valuesLocked: BigNumberish[],
      _reason: string,
      _releaseTimes: BigNumberish[]
    ],
    [boolean],
    "nonpayable"
  >;

  issueTokensWithNoCompliance: TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  omnibusBurn: TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _who: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  omnibusSeize: TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  preTransferCheck: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seize: TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  setCap: TypedContractMethod<[_cap: BigNumberish], [void], "nonpayable">;

  setDSService: TypedContractMethod<
    [_serviceId: BigNumberish, _address: AddressLike],
    [boolean],
    "nonpayable"
  >;

  setFeature: TypedContractMethod<
    [featureIndex: BigNumberish, enable: boolean],
    [void],
    "nonpayable"
  >;

  setFeatures: TypedContractMethod<
    [features: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedFeatures: TypedContractMethod<[], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalIssued: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateOmnibusInvestorBalance: TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _wallet: AddressLike,
      _value: BigNumberish,
      _increase: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  walletCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_CONFIGURATION_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COMPLIANCE_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DS_TOKEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OMNIBUS_TBE_CONTROLLER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARTITIONS_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTRY_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_EXCHANGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_ISSUER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_MASTER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_TRANSFER_AGENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECURITIZE_SWAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_ISSUER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_REALLOCATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRANSACTION_RELAYER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRUST_SERVICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNUSED_1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WALLET_MANAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WALLET_REGISTRAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [_owner: AddressLike, _spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [_spender: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[_owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfInvestor"
  ): TypedContractMethod<[_id: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [_who: AddressLike, _value: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseApproval"
  ): TypedContractMethod<
    [_spender: AddressLike, _subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitOmnibusTBEEvent"
  ): TypedContractMethod<
    [
      omnibusWallet: AddressLike,
      totalDelta: BigNumberish,
      accreditedDelta: BigNumberish,
      usAccreditedDelta: BigNumberish,
      usTotalDelta: BigNumberish,
      jpTotalDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitOmnibusTBETransferEvent"
  ): TypedContractMethod<
    [omnibusWallet: AddressLike, externalId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitOmnibusTransferEvent"
  ): TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDSService"
  ): TypedContractMethod<[_serviceId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWalletAt"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "increaseApproval"
  ): TypedContractMethod<
    [_spender: AddressLike, _addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize(string,string,uint8)"
  ): TypedContractMethod<
    [_name: string, _symbol: string, _decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueTokens"
  ): TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueTokensCustom"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _value: BigNumberish,
      _issuanceTime: BigNumberish,
      _valueLocked: BigNumberish,
      _reason: string,
      _releaseTime: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueTokensWithMultipleLocks"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _value: BigNumberish,
      _issuanceTime: BigNumberish,
      _valuesLocked: BigNumberish[],
      _reason: string,
      _releaseTimes: BigNumberish[]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueTokensWithNoCompliance"
  ): TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "omnibusBurn"
  ): TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _who: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "omnibusSeize"
  ): TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "preTransferCheck"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [[bigint, string] & { code: bigint; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seize"
  ): TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCap"
  ): TypedContractMethod<[_cap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDSService"
  ): TypedContractMethod<
    [_serviceId: BigNumberish, _address: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeature"
  ): TypedContractMethod<
    [featureIndex: BigNumberish, enable: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeatures"
  ): TypedContractMethod<[features: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedFeatures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalIssued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOmnibusInvestorBalance"
  ): TypedContractMethod<
    [
      _omnibusWallet: AddressLike,
      _wallet: AddressLike,
      _value: BigNumberish,
      _increase: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "walletCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Burn"
  ): TypedContractEvent<
    BurnEvent.InputTuple,
    BurnEvent.OutputTuple,
    BurnEvent.OutputObject
  >;
  getEvent(
    key: "DSServiceSet"
  ): TypedContractEvent<
    DSServiceSetEvent.InputTuple,
    DSServiceSetEvent.OutputTuple,
    DSServiceSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Issue"
  ): TypedContractEvent<
    IssueEvent.InputTuple,
    IssueEvent.OutputTuple,
    IssueEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusBurn"
  ): TypedContractEvent<
    OmnibusBurnEvent.InputTuple,
    OmnibusBurnEvent.OutputTuple,
    OmnibusBurnEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusDeposit"
  ): TypedContractEvent<
    OmnibusDepositEvent.InputTuple,
    OmnibusDepositEvent.OutputTuple,
    OmnibusDepositEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusSeize"
  ): TypedContractEvent<
    OmnibusSeizeEvent.InputTuple,
    OmnibusSeizeEvent.OutputTuple,
    OmnibusSeizeEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusTBEOperation"
  ): TypedContractEvent<
    OmnibusTBEOperationEvent.InputTuple,
    OmnibusTBEOperationEvent.OutputTuple,
    OmnibusTBEOperationEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusTBETransfer"
  ): TypedContractEvent<
    OmnibusTBETransferEvent.InputTuple,
    OmnibusTBETransferEvent.OutputTuple,
    OmnibusTBETransferEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusTransfer"
  ): TypedContractEvent<
    OmnibusTransferEvent.InputTuple,
    OmnibusTransferEvent.OutputTuple,
    OmnibusTransferEvent.OutputObject
  >;
  getEvent(
    key: "OmnibusWithdraw"
  ): TypedContractEvent<
    OmnibusWithdrawEvent.InputTuple,
    OmnibusWithdrawEvent.OutputTuple,
    OmnibusWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Pause"
  ): TypedContractEvent<
    PauseEvent.InputTuple,
    PauseEvent.OutputTuple,
    PauseEvent.OutputObject
  >;
  getEvent(
    key: "Seize"
  ): TypedContractEvent<
    SeizeEvent.InputTuple,
    SeizeEvent.OutputTuple,
    SeizeEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpause"
  ): TypedContractEvent<
    UnpauseEvent.InputTuple,
    UnpauseEvent.OutputTuple,
    UnpauseEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WalletAdded"
  ): TypedContractEvent<
    WalletAddedEvent.InputTuple,
    WalletAddedEvent.OutputTuple,
    WalletAddedEvent.OutputObject
  >;
  getEvent(
    key: "WalletRemoved"
  ): TypedContractEvent<
    WalletRemovedEvent.InputTuple,
    WalletRemovedEvent.OutputTuple,
    WalletRemovedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Burn(address,uint256,string)": TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;
    Burn: TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;

    "DSServiceSet(uint256,address)": TypedContractEvent<
      DSServiceSetEvent.InputTuple,
      DSServiceSetEvent.OutputTuple,
      DSServiceSetEvent.OutputObject
    >;
    DSServiceSet: TypedContractEvent<
      DSServiceSetEvent.InputTuple,
      DSServiceSetEvent.OutputTuple,
      DSServiceSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Issue(address,uint256,uint256)": TypedContractEvent<
      IssueEvent.InputTuple,
      IssueEvent.OutputTuple,
      IssueEvent.OutputObject
    >;
    Issue: TypedContractEvent<
      IssueEvent.InputTuple,
      IssueEvent.OutputTuple,
      IssueEvent.OutputObject
    >;

    "OmnibusBurn(address,address,uint256,string,uint8)": TypedContractEvent<
      OmnibusBurnEvent.InputTuple,
      OmnibusBurnEvent.OutputTuple,
      OmnibusBurnEvent.OutputObject
    >;
    OmnibusBurn: TypedContractEvent<
      OmnibusBurnEvent.InputTuple,
      OmnibusBurnEvent.OutputTuple,
      OmnibusBurnEvent.OutputObject
    >;

    "OmnibusDeposit(address,address,uint256,uint8)": TypedContractEvent<
      OmnibusDepositEvent.InputTuple,
      OmnibusDepositEvent.OutputTuple,
      OmnibusDepositEvent.OutputObject
    >;
    OmnibusDeposit: TypedContractEvent<
      OmnibusDepositEvent.InputTuple,
      OmnibusDepositEvent.OutputTuple,
      OmnibusDepositEvent.OutputObject
    >;

    "OmnibusSeize(address,address,uint256,string,uint8)": TypedContractEvent<
      OmnibusSeizeEvent.InputTuple,
      OmnibusSeizeEvent.OutputTuple,
      OmnibusSeizeEvent.OutputObject
    >;
    OmnibusSeize: TypedContractEvent<
      OmnibusSeizeEvent.InputTuple,
      OmnibusSeizeEvent.OutputTuple,
      OmnibusSeizeEvent.OutputObject
    >;

    "OmnibusTBEOperation(address,int256,int256,int256,int256,int256)": TypedContractEvent<
      OmnibusTBEOperationEvent.InputTuple,
      OmnibusTBEOperationEvent.OutputTuple,
      OmnibusTBEOperationEvent.OutputObject
    >;
    OmnibusTBEOperation: TypedContractEvent<
      OmnibusTBEOperationEvent.InputTuple,
      OmnibusTBEOperationEvent.OutputTuple,
      OmnibusTBEOperationEvent.OutputObject
    >;

    "OmnibusTBETransfer(address,string)": TypedContractEvent<
      OmnibusTBETransferEvent.InputTuple,
      OmnibusTBETransferEvent.OutputTuple,
      OmnibusTBETransferEvent.OutputObject
    >;
    OmnibusTBETransfer: TypedContractEvent<
      OmnibusTBETransferEvent.InputTuple,
      OmnibusTBETransferEvent.OutputTuple,
      OmnibusTBETransferEvent.OutputObject
    >;

    "OmnibusTransfer(address,address,address,uint256,uint8)": TypedContractEvent<
      OmnibusTransferEvent.InputTuple,
      OmnibusTransferEvent.OutputTuple,
      OmnibusTransferEvent.OutputObject
    >;
    OmnibusTransfer: TypedContractEvent<
      OmnibusTransferEvent.InputTuple,
      OmnibusTransferEvent.OutputTuple,
      OmnibusTransferEvent.OutputObject
    >;

    "OmnibusWithdraw(address,address,uint256,uint8)": TypedContractEvent<
      OmnibusWithdrawEvent.InputTuple,
      OmnibusWithdrawEvent.OutputTuple,
      OmnibusWithdrawEvent.OutputObject
    >;
    OmnibusWithdraw: TypedContractEvent<
      OmnibusWithdrawEvent.InputTuple,
      OmnibusWithdrawEvent.OutputTuple,
      OmnibusWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Pause()": TypedContractEvent<
      PauseEvent.InputTuple,
      PauseEvent.OutputTuple,
      PauseEvent.OutputObject
    >;
    Pause: TypedContractEvent<
      PauseEvent.InputTuple,
      PauseEvent.OutputTuple,
      PauseEvent.OutputObject
    >;

    "Seize(address,address,uint256,string)": TypedContractEvent<
      SeizeEvent.InputTuple,
      SeizeEvent.OutputTuple,
      SeizeEvent.OutputObject
    >;
    Seize: TypedContractEvent<
      SeizeEvent.InputTuple,
      SeizeEvent.OutputTuple,
      SeizeEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpause()": TypedContractEvent<
      UnpauseEvent.InputTuple,
      UnpauseEvent.OutputTuple,
      UnpauseEvent.OutputObject
    >;
    Unpause: TypedContractEvent<
      UnpauseEvent.InputTuple,
      UnpauseEvent.OutputTuple,
      UnpauseEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WalletAdded(address)": TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;
    WalletAdded: TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;

    "WalletRemoved(address)": TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;
    WalletRemoved: TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;
  };
}
