/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StandardTokenMock } from "./StandardTokenMock";
export type { TestCalls } from "./TestCalls";
export type { TestToken } from "./TestToken";
